### Creating adjacency matrix with pairwise distance between the elements in one tensor

In [1]:
import torch

In [2]:
TENSOR_SIZE = (5,3)
tensor = torch.rand(TENSOR_SIZE)
print(tensor)

tensor([[0.0199, 0.8751, 0.1139],
        [0.9096, 0.8300, 0.9274],
        [0.7109, 0.4133, 0.9727],
        [0.2511, 0.2100, 0.9174],
        [0.4060, 0.2329, 0.0783]])


In [3]:
num_elements = tensor.shape[0]
adjacency = torch.zeros((num_elements, num_elements))
print(adjacency)


tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [4]:
for element in range(num_elements):
    dist = torch.cdist(tensor[element,:].unsqueeze(0), tensor[element+1:,:] ,p=2)
    adjacency[element,element+1:] = dist
    adjacency[element+1:,element] = dist
    print(adjacency)

tensor([[0.0000, 1.2064, 1.1952, 1.0684, 0.7502],
        [1.2064, 0.0000, 0.0000, 0.0000, 0.0000],
        [1.1952, 0.0000, 0.0000, 0.0000, 0.0000],
        [1.0684, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.7502, 0.0000, 0.0000, 0.0000, 0.0000]])
tensor([[0.0000, 1.2064, 1.1952, 1.0684, 0.7502],
        [1.2064, 0.0000, 0.4639, 0.9045, 1.1537],
        [1.1952, 0.4639, 0.0000, 0.0000, 0.0000],
        [1.0684, 0.9045, 0.0000, 0.0000, 0.0000],
        [0.7502, 1.1537, 0.0000, 0.0000, 0.0000]])
tensor([[0.0000, 1.2064, 1.1952, 1.0684, 0.7502],
        [1.2064, 0.0000, 0.4639, 0.9045, 1.1537],
        [1.1952, 0.4639, 0.0000, 0.5058, 0.9620],
        [1.0684, 0.9045, 0.5058, 0.0000, 0.0000],
        [0.7502, 1.1537, 0.9620, 0.0000, 0.0000]])
tensor([[0.0000, 1.2064, 1.1952, 1.0684, 0.7502],
        [1.2064, 0.0000, 0.4639, 0.9045, 1.1537],
        [1.1952, 0.4639, 0.0000, 0.5058, 0.9620],
        [1.0684, 0.9045, 0.5058, 0.0000, 0.8535],
        [0.7502, 1.1537, 0.9620, 0.8535, 0.0000

In [5]:
print(adjacency)

tensor([[0.0000, 1.2064, 1.1952, 1.0684, 0.7502],
        [1.2064, 0.0000, 0.4639, 0.9045, 1.1537],
        [1.1952, 0.4639, 0.0000, 0.5058, 0.9620],
        [1.0684, 0.9045, 0.5058, 0.0000, 0.8535],
        [0.7502, 1.1537, 0.9620, 0.8535, 0.0000]])
